name: f1_app
description: "Simple F1 app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/teams/
    - assets/images/teams/sauber.png
  fonts:
    - family: f1
      fonts:
        - asset: assets/fonts/f1-font.otf
          weight: 400
        - asset: assets/fonts/f1-font.otf
          weight: 700
