name: f1_app
description: "Simple F1 app"
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  flutter_native_splash: 2.4.5
  flutter_launcher_icons: 0.14.3

flutter_native_splash:
  color: "#e6e6e6"
  image: "assets/images/f1-logo.png"
  ios: true
  android: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/f1-logo-filled.png"
  adaptive_icon_background: "#e6e6e6"
  adaptive_icon_foreground: "assets/images/f1-icon.png"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/teams/
    - assets/images/teams/sauber.png
  fonts:
    - family: f1
      fonts:
        - asset: assets/fonts/f1-font.otf
          weight: 400
        - asset: assets/fonts/f1-font.otf
          weight: 700
